name: flutter_design_viewer
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # internal
  flutter_design:
    path: ../flutter_design
  # framework
  flutter_hooks: ^0.18.2
  vrouter: ^1.2.0+21
  # state management
  hooks_riverpod: ^1.0.3
  # data
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  faker: ^2.0.0
  # font
  google_fonts: ^2.1.0
  # controls
  material_floating_search_bar: ^0.3.6
  linked_scroll_controller: ^0.2.0
  dotted_border: ^2.0.0+1
  device_preview: ^1.0.0
  clipboard: ^0.1.3
  expandable: ^5.0.1
  flutter_zoom_drawer: ^2.3.0
  flutter_markdown: ^0.6.9
  patterns_canvas: ^0.3.5
  # media
  flutter_svg: ^1.0.3
  flutter_feather_icons: ^2.0.0+1
  ionicons: ^0.1.2
  flag: ^6.0.0
  # notification
  bot_toast: ^4.0.1
  # media
  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.0
  # system
  url_launcher: ^6.0.18
  localstorage: ^4.0.0+1
  # meta
  analyzer: ^3.2.0
  string_similarity: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  # build
  build_runner: ^2.1.7
  # data
  freezed: ^1.1.1
  json_serializable: ^6.1.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/
    - assets/google_fonts/

  # Use Google Fonts manually via "fontFamily" because of this issue:
  # https://github.com/material-foundation/google-fonts-flutter/issues/35
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/google_fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/google_fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/google_fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/google_fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/google_fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/google_fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/google_fonts/Poppins-Black.ttf
          weight: 900
