name: flutter_design_codegen
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/ShiroYacha/flutter_design
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  analyzer: ^3.2.0
  build: ^2.2.1
  build_resolvers: ^2.0.0
  dart_style: ^2.2.1
  flutter_design_annotation:
    path: ../flutter_design_annotation
  glob: ^2.0.2
  path: ^1.8.0
  recase: ^4.0.0
  source_gen: ^1.2.1

dev_dependencies:
  lint: ^1.8.2
  test: ^1.20.1
