name: flutter_design_codegen
description: A new Flutter package project.
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  analyzer: ^3.2.0
  build_resolvers: ^2.0.0
  flutter_design_annotation:
    path: ../flutter_design_annotation
  recase: ^4.0.0
  source_gen: ^1.2.1
  build:
  dart_style:

dev_dependencies:
  lint: ^1.8.2
  test: ^1.20.1
